version: '3'
services:
    app:
        image: guoxiangke/gced
        build:
            context: .
            dockerfile: 'Dockerfile'
        restart: unless-stopped
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ./.env:/usr/src/app/.env
            # Uncomment 4 Dev
            # 把./bot排除在外，这样，每次修改代码，不用重复构建镜像，直接使用cache
            - ./bot:/usr/src/app/bot
            - ./grace.memory-card.json:/usr/src/app/grace.memory-card.json
            - ./sqlite/data/model.sqlite:/usr/src/app/sqlite/data/model.sqlite
            - ./bot/config:/usr/src/app/bot/config
            - ./files:/usr/src/app/files
            # - ./package.json:/usr/src/app/package.json
            # Uncomment on Local
            # - ../../../Downloads/Share/19_Psalm:/usr/src/app/files/19_Psalm # 4dev resources(mp3) for one cron task
