version: '3'
services:
    app:
        image: guoxiangke/gced
        build:
            context: .
            dockerfile: 'Dockerfile'
        restart: unless-stopped
        environment:
            - TZ=Asia/Shanghai
        volumes:
            # 把./bot排除在外，这样，每次修改代码，不用重复构建镜像，直接使用cache
            - ./bot:/usr/src/app/bot
            - ./package.json:/usr/src/app/package.json
            # - ./bot/config:/usr/src/app/bot/config
            # - ./bot/files:/usr/src/app/bot/files
            - ../../../Downloads/Share/19_Psalm:/usr/src/app/bot/files/19_Psalm # 4dev resources(mp3) for one cron task
            - ./.env:/usr/src/app/.env
